services:
  database:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    image: elixir:1.17
    command: >
      bash -c "mix setup && mix run priv/repo/seeds.exs && mix phx.server"
    working_dir: /app
    environment:
      DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      - database
  frontend:
    image: node:lts-bullseye
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: /bin/sh -c "npm install || true && npm run dev -- --host"
    
    # The 'command' directive overrides the default command specified by the Docker image.
    # In this case, it runs 'tail -f /dev/null', which keeps the container running indefinitely
    # by continuously monitoring an empty file. We used it to build the initial project.
    # command: tail -f /dev/null

volumes:
  postgres_data:
