services:
  database:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    image: elixir:1.17
    command: >
      bash -c "mix setup && mix phx.server"
    working_dir: /app
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      - database
