services:
  database:
    image: postgres:17
    container_name: t-poo-700-stg_9_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    image: elixir:1.17
    container_name: t-poo-700-stg_9_backend
    command: >
      bash -c "mix setup && mix run priv/repo/seeds.exs && mix phx.server"
    working_dir: /app
    environment:
      DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      - database
  frontend:
    image: node:lts-bullseye
    container_name: t-poo-700-stg_9_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: /bin/sh -c "npm install && npm run dev -- --host"
volumes:
  postgres_data:
    name: t-poo-700-stg_9_postgres_data
