entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: hibobo@kurama-chat.xyz
      storage: /acme/acme.json
      tlsChallenge: {}

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: true

log:
  level: DEBUG

accessLog: {}
