name: Generate Badges

on:
  push:
    branches:
      - main

jobs:
  generate-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate latest tag badge
        id: latest-tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "none")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
          echo "![Latest Tag](https://img.shields.io/badge/latest%20tag-$latest_tag-blue)" > latest-tag-badge.md

      - name: Generate workflow status badge
        id: workflow-status
        run: |
          echo "![GitHub Workflow Status](https://img.shields.io/github/actions/workflow/status/EpitechMscProPromo2026/T-POO-700-STG_9/main.yml?branch=main&label=build)" > workflow-status-badge.md

      - name: Commit and push badges
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add latest-tag-badge.md workflow-status-badge.md
          git commit -m "Update badges"
          git push
